services:
  fastapi:
    image: shubhamrelanto/fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  streamlit:
    image: shubhamrelanto/streamlit:v1
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    environment:
      API_URL: http://fastapi:8000